services:
  - type: static
    name: etr-plants-agri-business
    env: static
    buildCommand: echo "Building static site"
    staticPublishPath: .
    routes:
      - path: /
        match: all
        increment: none
